package com.example.lungsguardian.utils

const val VALIDATE_EMAIL_NULL = "email error"
const val VALIDATE_FULL_NAME_NULL = "name error"
const val VALIDATE_PHONE_NULL = "phone error"
const val VALIDATE_PASSWORD_NULL = "password error"
const val VALIDATE_PASSWORD_CONFIGURATION_NULL = "password configuration error"
const val VALIDATE_PASSWORD_DOESNT_MATCH_PROBLEM = "password doesn't match error"
const val VALIDATE_CODE_NULL = "code error"
const val VALIDATE_EMAIL_INVALID = "invalid email format"
const val VALIDATE_FULL_NAME_INVALID = "full name must contain at least two names"
const val VALIDATE_PHONE_INVALID = "phone number must be 11 digits"
const val VALIDATE_PASSWORD_INVALID =
    "password must contains 1 Uppercase, 1 Lowercase, 1 Digit, 1 Special Character"
const val VALIDATE_CODE_INVALID = "code must be 6 digits"
const val SEND_CODE_DONE = "Password reset code sent to your email"
const val SEND_CODE_Failed = "Email is Not Exist"
const val SHARED_PREFERENCES_NAME = "Lungs"
const val USER_NAME = "user name"
const val USER_EMAIL = "user email"
const val USER_PHONE = "user name"
const val LOGGED_STATE = "user log state"
const val LOGGED_IN = "user logged in"
